apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Namespace
    metadata:
      name: ns1

  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: ns1
      namespace: ns1
    spec:
      hard:
        pods: '4'
        requests.cpu: '1'
        requests.memory: 1Gi
        limits.cpu: '2'

  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: mem-limit-range
      namespace: ns1
    spec:
      limits:
        - default:
            memory: 512Mi
          defaultRequest:
            memory: 256Mi
          type: Container

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: rest
      namespace: cengiz
    spec:
      podSelector: {}
      policyTypes:
        - Ingress
        - Egress
